apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
data:
  sshPrivateKey: ...
stringData:
  url: ...