name: Deploy Infra and ArgoCD

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Terraform Apply
        run: |
          cd terraform-infra
          terraform init
          terraform apply -auto-approve -var-file="environments/dev/terraform.tfvars"

  deploy-argocd:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-gitops-dev \
            --name aks-dev \
            --overwrite-existing

      - name: Deploy ArgoCD
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Apply root ArgoCD app
        run: kubectl apply -f environments/dev/root-application.yaml